import "./globals.css";
import "../assets/iconfont/iconfont.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Navigation from "@/app/components/navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        <Navigation/>
        <div className="pt-24">{children}</div>
        </body>
        </html>
    );
}
